### ISSUE TITLE
How to run shinyjs::html on page load?

### ISSUE THREAD

**Issue by emillykkejensen** [daattali/shinyjs#102]
Hi. Thanks for a great package.

I can't seem to use shinyjs::html on page load when using htmlTemplate(). However when wrapping it in a observeEvent() it works! What to do?

-----------------------------------
app.R
```
library(shiny)
library(shinyjs)

shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))

ui <- htmlTemplate("temp.html", content = htmlOutput("content"))


server <- function(input, output) {
  
  useShinyjs(html = TRUE)
  
  output$content <- renderUI(includeHTML("content.html"))
    
  shinyjs::html(id = "text", html = "Test for text")
  
  observeEvent(input$button, {
    shinyjs::html(id = "text", html = "Test for text")
  })
  
}
shinyApp(ui, server)
```
-----------------------------------
temp.html
```
<html>
  <head>
    {{ headContent() }}
	<script src="shinyjs/inject.js"></script>
    <link rel="stylesheet" type="text/css" href="shared/shiny.css"/> 
  </head>
   
  <body>
    <h1>Test</h1>
	
	{{ content }}
    
  </body>
</html>
```
-----------------------------------
content.html
```
	<button id="button" type="button" class="action-button shiny-bound-input">Button</button>
	
	<pre id="text" class="shiny-text-output"></pre> 
```

**Comment by daattali** [comment]
This probably isn't working because at the time that you're calling the `html()` function, the `text` element doesn't exist yet. In the previous line you're telling shiny to add some HTML into the page, but that doesn't happen instantly because of the way shiny works. Unfortunately this is how shiny is designed (correctly so - it makes shiny a lot faster and more responsive by now sending all messages all the time the exact moment they're called), but from time to time you'll run into issues such as this.

I think you could get around this problem by putting the `html()` call inside a `shinyjs::delay()`. That's not what the delay function was meant for, but I think it would work

**Comment by emillykkejensen** [comment]
Perfect! That works :-)
