### ISSUE TITLE
fileInput() value is not reset when reset() is called on it.

### ISSUE THREAD

**Issue by molx** [daattali/shinyjs#104]
`reset()` is a very useful function, but it appears to not work correctly/completely for `fileInput()`

Even though it resets the view of the input, its value does not become null again, making it rather pointless.  Check this example, where the file name persists (along with everything else) even after the input is reset.

```
library(shiny)
library(shinyjs)

shinyApp(ui = shinyUI(
  bootstrapPage(useShinyjs(),
                actionButton("fname", "View File Name"),
                textOutput("out"),
                fileInput("inpt", "Input"),
                actionButton("rst", "Reset")) 
),
server = function(input, output, session) {
  observeEvent(input$rst, {
    reset("inpt")
    output$out <- renderText("")
  })
  
  observeEvent(input$fname, {
    output$out <- isolate(renderText(input$inpt$datapath))
  })
})
```

The way I see it, after calling `reset()` the value of `inpt` should be `NULL`.

**Comment by daattali** [comment]
This is a known problem and I don't think there's a reasonable way to fix it. If you google around for resetting file inputs (in html/javascript in general, not just in shiny) you'll see it's a very common and frustrating problem with no real ideal solution.  For a very long time I didn't want to even support fileInputs in shinyjs reset at all because it wouldn't be able to do exactly what you describe - to set the input to NULL in R. But I've had dozens of people ask me for the other half of the reset problem: after uploading a file, they want the file input UI to be reset so that if you try to upload the same file again, it'll let you. This is a much more common problem than the one you're describing, and that one does work Hence I wouldn't say it's currently "useless" :)

But what you want to do, which is to take the reset function for files until the very end, I unfortunately can't do.

**Comment by molx** [comment]
I see, have been to those google results a few times now over the past months. Even though I understand you're not working on this now (since it's more complicated than it looks) I look forward to the day a solution for all situations is found. Still, great work with the function and the package in general.

**Comment by daattali** [comment]
It's been an annoyance with web dev for many years and I doubt it'll change soon. Just one of the many things in HTML that everyone needs to work around :)
