### ISSUE TITLE
reset doesn't respect inputs in modals

### ISSUE THREAD

**Issue by carlganz** [daattali/shinyjs#119]
MRE:

```{R}
library(shiny)
library(shinyjs)

ui <- fluidPage(
  useShinyjs(),
  actionButton("press", "Press me to reset input in modal")
)

server <- function(input, output, session) {
  showModal(
    modalDialog(
      textInput("one", "Enter some text here")
    )
  )
  
  observeEvent(input$press, {
    reset("one")
    print(input$one)
  })
  
}

shinyApp(ui=ui,server=server)
```

Enter some text into the text input in the opening modal. Then close the modal and press the button which triggers `reset`. `input$one` retains its value. This is likely because the actual input is no longer in the HTML once the modal is removed. 

Thanks

**Comment by daattali** [comment]
You're right, it happens because the input itself is removed from the DOM and doesn't exist. This is unfortunately something that I don't think can be fixed from shinyjs's side. Modals in shiny are a bit awkward and I've run into my fair share of problems with them too, I guess this one is another minor one to add to the list :)
