### ISSUE TITLE
hide and show tabsetPanel

### ISSUE THREAD

**Issue by GeraldCNelson** [daattali/shinyjs#121]
I'm trying to use the hide/show structure in SO link below, but I want to show a tabsetPanel.
http://stackoverflow.com/questions/35599470/shiny-dashboard-display-a-dedicated-loading-page-until-initial-loading-of

The following code snippet is from the app.R file in the GitHub project https://github.com/GeraldCNelson/nutmod.

(https://github.com/GeraldCNelson/nutmod/blob/master/nutrientModeling/app.R)

The 'loading_page' works correctly, but when the tabsetPanel id = "mainTabsetPanel" is called with 
 ```
hide("loading_page")
  shinyjs::show("mainTabsetPanel")
```
the tabs don't show up. I just get a blank web page.

```
ui <- fluidPage(
   theme = shinytheme("cerulean"),
   title = "Nutrient modeling",

  useShinyjs(debug = TRUE),
  div(
    id = "loading_page",
    #    h1("Loading...")
    includeHTML("www/introText.html")
  ),
  hidden(
    div(
      tabsetPanel(id = "mainTabsetPanel",
                  # Introduction tab panel -----
                  tabPanel(title = "Introduction",
                           mainPanel(width = "100%",
                                     includeHTML("www/introText.html")
                           )),
```
Any suggestions greatly appreciated!

**Comment by daattali** [comment]
Hi

I'm not near a computer so I haven't run your code. But I can tell you that
using show/hide on a tabPanel ID won't work, because when shiny builds a
tabset panel there is some other HTML that gets built in the way. What this
"hidden()" does is it hides the parent of the tabset panel, and when you
later say "show(tabsetpanel)" that works but the parent is still hidden.

I think the simple solution here is giving an id to the div , and calling
show() on that div's ID rather than the tabsetPanel's ID

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by GeraldCNelson** [comment]
That did the trick. If its ok, I'll post a question and answer in SO. Thanks!
