### ISSUE TITLE
showElement not showing a hidden object

### ISSUE THREAD

**Issue by KZARCA** [daattali/shinyjs#123]
Hi Dean,
I wrote a code similar to the following one. The idea is to show a div when calculation is being performed.

```
library(shiny)
library(shinyjs)
ui <- fluidPage(
  useShinyjs(),
  actionButton("clickTest", "Start"),
  hidden(
    uiOutput("outWait")
  )
)

server <- function(input, output) {
  observeEvent(input$clickTest,{
    print("Start Wait")
    showElement("outWait")
    Sys.sleep(2)
    print("End Wait")
    hideElement("outWait")
  })
  
  output$outWait <- renderUI({
    icon(name = "spinner", class = "fa-pulse fa-2x")
  })
}

shinyApp(ui = ui, server = server)

```

The first time I click on "Start" Button, it does not show "outWait"; the second time, it shows "outWait".
Do you understand why?

Cheers!

**Comment by daattali** [comment]
Unfortunately this is more of a shiny issue than shinyjs. What's happening in your code is that the instruction to show the element happens immediately, but the element is empty so you don't see anything. The reactive `outWait` element output only runs when the entire code block inside the button click observer finishes executing.

To show that this is what's happening, here is your code, with two additions: I put a print statement inside the `renderUI()` so that you can see when it gets executed, and I also added another hidden element that gets shown at the same time, and you'll see that because it's not reactive it does show up immediately.

```
library(shiny)
library(shinyjs)
ui <- fluidPage(
  useShinyjs(),
  actionButton("clickTest", "Start"),
  hidden(
    div(id = "foo", "bar"),
    uiOutput("outWait")
  )
)

server <- function(input, output) {
  observeEvent(input$clickTest,{
    print("Start Wait")
    showElement("outWait")
    showElement("foo")
    Sys.sleep(2)
    print("End Wait")
    hideElement("outWait")
  })
  
  output$outWait <- renderUI({
    print("render")
    icon(name = "spinner", class = "fa-pulse fa-2x")
  })
}

shinyApp(ui = ui, server = server)
```

I can replicate this behaviour without shinyjs as well:

```
library(shiny)

ui <- fluidPage(
  useShinyjs(),
  actionButton("btn", "Click"),
  uiOutput("out")
)

server <- function(input, output) {
  values <- reactiveValues(foo = NULL)
  
  observeEvent(input$btn, {
    print("Start Wait")
    values$foo <- "bar"
    Sys.sleep(2)
    print("End Wait")
  })
  
  output$out <- renderUI({
    values$foo
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment]
@KZARCA I asked about this on the shiny forum and Joe agreed it might be useful to control this behaviour, so this is now an issue on shiny https://github.com/rstudio/shiny/issues/1705

**Comment by KZARCA** [comment]
Thanks!
I understand where the problem is: when I invert my code, by not hiding the "outWait" in ui; hiding it on click and showing at the end of the observer, it works!
I'm very probably wrong, but the example without shinyjs seems to be a different problem to me, as showElement and hideElement are executed immediately (it's just that showElement cannot show an element which does not exist), but the assignment of values$foo is done at the end).

**Comment by daattali** [comment]
The example without shinyjs is showing the same problem that happens in your code. In both cases, what happens is that any reactive outputs only get calculated after the entire code block in the observer gets executed.

In your case, what happens is: the output gets shown (but it's empty so you don't notice it), then you wait 2 seconds, then the output gets rendered, but immediately after that you call hide so it gets hidden. Next time you click on the button, again show() happens right away, and this time there's already content so you see it, then waits 2 seconds, then the output is rendered again (identical to what's already there), then it gets hidden.

What you described is incorrect - showElement and hideElement are **not** executed immediately. There is a 2second delay between them. Also, the element DOES exist, it just doesn't have anything inside of it.

Reactivity is quite a complex topic, definitely the hardest to grasp in shiny, it's a bit confusing. I'm closing this issue because this is a shiny issue and not something I can do from shinyjs
