### ISSUE TITLE
Feature request: Collapsible menu items in Inputs

### ISSUE THREAD

**Issue by philstraforelli** [daattali/shinyjs#128]
Let's say I have a bunch of different inputs such as the following:

    checkboxGroupInput("sex", label = "Gender", choices = c("Male", "Female"), selected = c("Male", "Female"))
    checkboxGroupInput("age3", label = "Age", choices = c("18-34", "35-54", "55+"), selected = c("18-34", "35-54", "55+"))

etc. etc.

And there enough of these down the sidebar that a scrollbar needs to be displayed on the client's end. It would be a useful feature to have a `shinyjs` option that collapses the choices down to only its header. So the "Age" header is displayed on its own, and only when the end user clicks on the header (or perhaps hovers on it) would it expand to show all the choices under "Age".

**Comment by daattali** [comment]
Hi @philstraforelli 

Thanks for the suggestion, but this sounds like too specific of a usecase, I don't think it's generally applicable to a wide range of people. shinyjs is meant to facilitate doing things that are **common** to do in web apps with javascript, and this is not something that I think falls under that category. I understand your need for this, but I try to be conservative in what features I add to shinyjs so that it won't lose its focus and become a place that just hosts a lot of random features.

I don't know your exact usecase, but perhaps look into the `shinyTree` package, or maybe even at selectInput with `optgroup` (it's a fairly unknown feature of select inputs that lets you group several inputs together under one heading)

**Comment by philstraforelli** [comment]
No worries, thanks for the quick response.
