### ISSUE TITLE
reset stops when it encounters radioButtons input with selected = NA 

### ISSUE THREAD

**Issue by tbradley1013** [daattali/shinyjs#142]
I am building an app that utilizes several `shinyjs` functions. I have one into one thing that may be intentional or may be a bug. My app has a large number of `textInput()` values and `radioButtons()` inputs. For the `radioButtons()` inputs, the choices are `list("Yes" = TRUE, "No" = FALSE, "N/A" = NA)`, and `selected = NA`. I have it set this way as the inputs are taken from a form that occasionally has options that are unselected. My issue is that when I have `selected = NA` as the option in the `radioButtons()` function, the `reset()` function will not reset any inputs after the radio button ui. In addition to not resetting any of the ui inputs after the radio buttons, it also does not reset the radio button back to "N/A". 

I have created a minimal example:

    library(shiny)
    library(shinyjs)

    ui <- shinyUI(
      fluidPage(
        useShinyjs(),
        div(
          id = "ex-main-div",
          div(
            id = "ex-nested-div-1",
            textInput(
              inputId = "ex_first_name",
              label = "First Name",
              value = NULL
            ),
            textInput(
              inputId = "ex_last_name",
              label = "Last Name",
              value = NULL
            )
          ),
          div(
            id = "ex-nested-div-2",
            textInput(
              inputId = "ex_age",
              label = "Age:",
              value = NULL
            ),
            radioButtons(
              inputId = "ex_legal",
              label = "Is over 21?",
              choices = list("Yes" = TRUE, "No" = FALSE, "N/A" = NA),
              selected = NA,
              inline = TRUE
            ),
            textInput(
              inputId = "ex_fav_drink",
              label = "Favorite Drink:",
              value = NULL
            )
          ),
          actionButton(
            inputId = "ex_reset",
            label = "Reset Inputs"
          )
        )
      )
    )

    server <- shinyServer(function(input, output){
      observeEvent(input$ex_reset, {
        shinyjs::reset("ex-main-div")
      })
    })

    shinyApp(ui = ui, server = server)

If you run this app, fill in all of the text boxes, change which option is selected for whether the person is "legal", and then press the reset button, only the ui input above the radio button will be reset. However, if you change `selected = NA` to `selected = FALSE` or `selected = TRUE` in the `radioButtons()` input than all of the inputs, including the `radioButtons()` input, are reset. I would like to use the N/A option as the default option in my app to prevent accidentally marking something as either TRUE or FALSE when no answer was actually given. Is this possible, or should I just change what the default option is? 

On an unrelated note, love this package and all of your tips and tricks on your [advanced shiny](https://github.com/daattali/advanced-shiny) repo!

**Comment by daattali** [comment]
Thanks for the report and the very detailed info and example!

After investigating it a little bit, unfortunately it seems like this is something that is partly caused by how NA values in radio buttons are handled by shiny. Frankly, I'm not sure if radio buttons are meant to support NA buttons explicitly, it seems like something that might not be recommended... If you look at the HTML output of radio buttons, when you give a choice the value of `NA`, in the HTML output it actually gives it no value. As in, the `value` HTML attribute actually have no corresponding value. I could make shinyjs explicitly look out for such a case and assume that no value means `NA`, but I would rather not go out of the way to support something like that. You could ask the shiny devs (for example on the shiny github repo or on https://groups.google.com/forum/#!forum/shiny-discuss) is I am correct that NA should not be given to radio choices, or perhaps I'm wrong.

As far as a solution, I can suggest a small workaround of using the string `"NA"` instead of an actual `NA` value, and in your server code check for "NA". I hope that helps!
