### ISSUE TITLE
Horrible performance due to MutationObserver

### ISSUE THREAD

**Issue by flying-sheep** [daattali/shinyjs#143]
Hi, I profiled my app and noticed that it performs horribly due to

1. DataTable having bad rendering performance
2. your MutationObserver making things worse

probably fixing 1. would be best, but as 2. had more impact, i removed shinyjs instead.

i’d prefer shinyjs to work without a MutationObserver.

**Comment by daattali** [comment]
I can certainly understand mutationobserver can affect the performance.

The initial versions of shinyjs did not have them, but I was getting a lot of reports on functions not working on dynamically generated elements. The purpose of the mutationobserver is that disabled()/reset()/onevent() would work on any elements even if they were not in the initial UI.

**Comment by daattali** [comment]
I can certainly understand mutationobserver can affect the performance. How much does it affect your performance?

A bit of background: The initial versions of shinyjs did not have them, but I was getting a lot of reports on functions not working on dynamically generated elements. The purpose of the mutationobserver is that disabled()/reset()/onevent() would work on any elements even if they were not in the initial UI.

Do you have a proposed alternative?

Brainstorming ideas (not sure how feasible they are, just throwing anything I can think of out there):

- shinyjs was built before shiny had its JavaScript events. Maybe shinyjs can use those events to know when new elements are added
- maybe a boolean flag can be used at initialization to tell shinyjs to not worry about new elements. Though this has the obvious flaw that noe anything that renders dynamically can't use some shinyjs functions
- perhaps there can be a sort of "shinyjs flush" function that can be called on demand and whenever it's called all elements are inspected , instead of inspecting every new 

IIf you have a suggestion please do share

**Comment by flying-sheep** [comment]
> How much does it affect your performance?

a 1s freeze due to DataTable’s DOM manipulation becomes a 2-3s freeze.

> shinyjs was built before shiny had its JavaScript events. Maybe shinyjs can use those events to know when new elements are added

that’s what i was counting on. if there are no such events, we should add them.

**Comment by daattali** [comment]
Just curious, how big is your datatable (how many rows and columns are
being shown)? Would it be possible to show a minimal reproducible example?

I'm really swamped with tons of work projects and issues on other OSS so I
don't think realistically I'll have time any time soon to take a look at
this. You're welcome to attempt to submit a PR if you'd like to

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by flying-sheep** [comment]
11,678 rows × 37 cols

but shouldn’t stuff be sent paginated? switching pages also takes a bit of time, but doesn’t show the “Processing…” badge and doesn’t freeze the tab.

**Comment by daattali** [comment]
Yes with DT usually you don't show all the rows at once, that's what I
meant - how many elements are actually in the DOM at any point? How many
rows are shown? And when do you notice the slowness, when you try to
paginate the table, or is it with other interactions in the app as well?

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by flying-sheep** [comment]
sorry: i set it to 100 rows, but i still get the “Processing…” thing when using 10.

the slowness is apparent when paginating or redrawing the table (usually because some reactive expression i use for filtering becomes invalidated).

**Comment by daattali** [comment]
Could you please share a minimal reproducible example,  it'll help anyone
trying to fix it see the issue.

**Comment by flying-sheep** [comment]
sure, if you can point me to some browser automation that i can use to measure the time between the typing of a letter and until the data table has finished updating.

that would be a starting point that allows me to do this without wasting a whole day staring at a frozen browser, changing a line, and checking again.

**Comment by daattali** [comment]
1. I think the approach I would try first is to be very low tech. Use
JavaScript to record when I type a letter and use the datatable completion
event to record when it's done. I haven't looked at DT documentation in a
while but I recall there being JavaScript events getting triggered when for
example the table is finished redrawing. There could very well be a better
way to debug this, that's the first simple thing that comes to mind
2. If it takes a really long time, maybe subset your data to a point where
paginating and debugging takes a reasonable amount of time

Even if you aren't able to debug and fix this, a code example of this
happening would help others who might tackle it in the future

**Comment by daattali** [comment]
@flying-sheep Let me know if there's any progress on this!

**Comment by daattali** [comment]
@flying-sheep let me know if you have any updates on either debugging or having an idea of what the desired behaviour should be. Without mutationobserver, shinyjs would not work on elements that are not present on page load

**Comment by daattali** [comment]
A reproducible example code would also help

**Comment by flying-sheep** [comment]
Hi! Unfortunately I don’t work on that project anymore, thus the radio silence.

I think what I did was a search field that filtered the data used in DataTable. Even when not displaying the whole data but only some 100 rows, DataTable still needed a lot of time to render (since it mutates a lot of DOM at once), and with the added MutationObserver, that rendering time increased a lot.

Are there no “finished updating” events from shiny that could be used instead?

**Comment by daattali** [comment]
Yes there are, I'm not sure if they'd work as easily because this tells me exactly what elements to look at, but it's possible. I wanted to have a testcase to test against if I were to try to fix the issue.

Thanks for your input, I'll keep the issue open so that the next person that finds shinyjs slow can comment here :)

**Comment by daattali** [comment]
@flying-sheep there has been a PR that attempts to solve some performance issues. Would you mind seeing if it fixed your issue as well?

**Comment by flying-sheep** [comment]
As said, I don’t work on that anymore. The PR seems to address the exact problem I had, so I’ll close this!
