### ISSUE TITLE
Conflict between README and LICENSE on commercial use 

### ISSUE THREAD

**Issue by malexan** [daattali/shinyjs#145]
README says:

> shinyjs was developed for non-commerical purposes. For commerical usage, please contact me.

("commerical" has a typo here, right? I suppose, it means "commercial"). 

On the other hand GNU Affero General Public License v3.0, as I understand, allows commercial use without notice of author.

**Comment by malexan** [comment]
Based on [this](https://softwareengineering.stackexchange.com/a/314908) I have to publish only the source code of modified AGPL3-licensed work. So if I use such work without modification and don't mix its code with my own code I don't need to publish anything. Right?

**Comment by daattali** [comment]
There are more considerations than that. Anyway, Stackoverflow and online
forums are not the place to get legal advice, which is why I seeked out a
tech lawyer to handle this. I'm not planning on trying to sue anyone and I
don't have the resources or the will to enforce the license too strictly,
it's simply a way to offer profitable companies who make use of shinyjs a
way to help pay for its development and give them a commercial so that they
can use shinyjs without restriction.

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by malexan** [comment]
> it's simply a way to offer profitable companies who make use of shinyjs a way to help pay for its development and give them a commercial so that they can use shinyjs without restriction.

This message doesn't sound clear to me. README says "For commercial usage, please contact me." It doesn't include any conditions about profitability etc. So developers, who want to build a commercial solution but don't want to clarify such foggy price policy of shinyjs, could prefer another solution (if it existed :) ). 

I would change the message and only keep the part about donation.

Thank you for your awesome products!

**Comment by daattali** [comment]
I wanted the note to be concise, I figured just saying "contact me" is the
simplest. I also don't say on my website that I work at a discount for
academics and non profits, I don't want to have to commit to anything
written so I prefer to tell people when they message me

On Nov 9, 2017 01:59, "Alexander Matrunich" <notifications@github.com>
wrote:

it's simply a way to offer profitable companies who make use of shinyjs a
way to help pay for its development and give them a commercial so that they
can use shinyjs without restriction.

This message doesn't sound clear to me. README says "For commercial usage,
please contact me." It doesn't include any conditions about profitability
etc. So developers, who want to build a commercial solution but don't want
to clarify such foggy price policy of shinyjs, could prefer another
solution (if it existed :) ).

I would change the message and only keep the part about donation.

Thank you for your awesome products!

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/daattali/shinyjs/issues/145#issuecomment-343064737>,
or mute
the thread

**Comment by daattali** [comment]
@malexan text was updated to "shinyjs is under the AGPL-3 license. For a commercial license, please contact me."
