### ISSUE TITLE
shinyjs::disable issue when using renderUI

### ISSUE THREAD

**Issue by jyjek** [daattali/shinyjs#166]
When I try use shinyjs::disable with renderUI it didn't work.
Thx!

```
  library(shiny)
  library(shinyjs)
  ui <- fluidPage(
    useShinyjs(),
    uiOutput("id1"),
    actionButton("id2","No render")
  )
  
  server <- function(input, output, session) {

  output$id1=renderUI({
      actionButton("id0","renderUI")
    })

    shinyjs::disable("id0")
    shinyjs::disable("id2")

  }
  
  shinyApp(ui, server)
```

**Comment by daattali** [comment]
That's not a bug, the disable function gets called as soon as the app
initializes, before the dynamic button exists. You can use the disabled()
function to create a tag that is initialized as disabled, or you can use
the delay() function to call disable after a short delay to give the button
a chance to render

**Comment by melissagwolf** [comment]
@daattali I have an app that runs simulations of varying times. I want to click on the download button when the app is finished running, but it is in a `renderUI` object so `shinyjs::click()` doesn't work. I can't use `shinyjs::delay()` because the delay time is extremely variable. I tried using `disabled()` with a subsequent `observeEvent()`, but it is still clicking before the button finishes rendering. Any ideas?
