### ISSUE TITLE
Adding multiple onclick events in a for loop leads to strange behaviour

### ISSUE THREAD

**Issue by BartJanvanRossum** [daattali/shinyjs#167]
When trying to add onclick events to multiple selectizeInputs in a for loop I ran into strange behaviour.  Doing the same using lapply looked works perfectly fine. 

When using a for loop the result is that if I click the first input the value of the second input is set to "".  Clicking the second input also sets the second input to "". 
I expected that clicking the first input would set the first input and clicking the second input set the second input. This is what happens when I use lapply.

In my real code I have a lot more inputs and there when using the for loop, always the last input gets set to "" no matter which one I click.

To me this seems to be a bug, but I might be missing something.

```
library(shiny)
library(shinyjs)
ui <- fluidPage(
  useShinyjs(),
  selectizeInput("id1", label = "input1", choices = c("", "A", "B"), selected = "A"),
  selectizeInput("id2", label = "input2", choices = c("", "A", "B"), selected = "B")
)

server <- function(input, output, session) {
  ids <- c("id1", "id2")
  ## This works perfectly fine
  lapply(X = ids, FUN = function(id) {
    shinyjs::onclick(id, {
      updateSelectizeInput(session = session, inputId = id, selected = "")
    })
  })
  ## Whereas this doesn't
  #for (id in ids) {
  #  shinyjs::onclick(id, {
  #    updateSelectizeInput(session = session, inputId = id, selected = "")
  #  })
  #}
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
Thanks for the report! Looks like this might be a environment/scope issue. I don't have time in the near future to look into it too much further, I would be happy to accept a PR

**Comment by thothal** [comment]
I had a look at the code and could identify the problem. In principle the problem arises, because `id` is not evaluated before `updateSelectizeInput` is triggered by the `onclick` event. At this point the `for` loop is already finished, and `id` took its final value (which is the last element of `ids`). 

So what we would need to do is to substitute  `id` in the `updateSelectizeInput` call by its actual value. I am not sure whether this can be done easily on the `shinyjs` side (basically there we would need to know which parts of the call should be replaced and which not). Replacing the values on the `server` side (using `substitute`) seems thus to be the solution. But for that we would need an adaptation of the `onclick` function to avoid another call to `substitute`.

To make a long story short the following code works, but it feels a bit hackish to me:

```
onclick_ <- function(id, expr, add = FALSE, asis = FALSE) {
   ## replace substitute(expr) by expr as we did the substitution on the caller side
   shinyjs:::oneventHelper("click", id, expr, add = add,
                           properties = NULL, asis = asis) 
}

server <- function(input, output, session) {
  ids <- c("id1", "id2")
  for (id in ids) {
     expr <- substitute(updateSelectizeInput(session = session, inputId = id, selected = ""),
                        list(id = id))
     onclick_(id, expr)
  }
}
```

**Comment by daattali** [comment]
Is that essentially the equivalent of the `quoted` parameter in shiny's `observe()` and `reactive()`? If so, I would prefer to add it as a parameter to closely match shiny's way of doing things. It would also need to get tested rigorously in different scenarios, in modules, when it's being called from nested functions, etc, because once you're dealing with environments and quoted text you want to make sure all bases are covered

**Comment by thothal** [comment]
Yet another workaround for this problem would be to use a `local` construct in the `for` loop, to make sure that `id` is evaluated at the right moment (i.e. in the right environment):

```
library(shiny)
library(shinyjs)
ui <- fluidPage(
  useShinyjs(),
  selectizeInput("id1", label = "input1", choices = c("", "A", "B"), selected = "A"),
  selectizeInput("id2", label = "input2", choices = c("", "A", "B"), selected = "B")
)

server <- function(input, output, session) {
  ids <- c("id1", "id2")
  for (id in ids) {
    local({
      my_id <- id
      shinyjs::onclick(id, {
        updateSelectizeInput(session = session, inputId = my_id, selected = "")
      })
    })
  }
}
shinyApp(ui, server)
```

**Comment by daattali** [comment]
Closing this issue as it's an R issue
