### ISSUE TITLE
Correct "smart-quotes" in runCode

### ISSUE THREAD

**Issue by gwarnes-mdsol** [daattali/shinyjs#170]
In using `runCode`, I keep running into problems because my system/browser is automagically converting single and double quotes to the equivalent UTF open and close pairs.    When the string is handed to R for evaluation, it gets unhappy.

For example, typing this manually in a `shinyjs::runcodeUI(..,type="textarea")`: `shinyjs::alert(“Boo!”)` and then clicking `run` yields:
```
Oops, that resulted in an error! Try again.
Error: 
:1:16: unexpected input 1: shinyjs::alert( ^
```

It would be helpful if runCode converted the UTF open/close quote symbols back to appropriate "standard" ASCII single/quote characters.

**Comment by daattali** [comment]
Interesting. Are you not running into issues in other places when programming in R? Do these quotes not become a problem when you try to type strings in R for example?

**Comment by daattali** [comment]
I wouldn't feel comfortable just blindly converting all instances of one character to another, the user may explicitly want the special character. I thought about it some more and it really doesn't seem like it should be considered a shinyjs issue and I don't think it'd be a good idea to make shinyjs assume this job

**Comment by gwarnes-mdsol** [comment]
The smart-quote translation isn't happing in any of my programming tools, only in the browser and word-processors.  

In another place in this application users provide the model expression or subset expression that is being passed onto R*.  I've handled this issue there by using this function:

```
to_ascii <- function(x) stri_trans_general(x, "Any-Latin; Latin-ASCII")
```

I understand the reluctance to 'blindly' translate characters.  It would make sense to set this up as an optional feature enabled via a function argument, perhaps named `convert_to_ascii`.

Another possibility is to provide an argument that allows the user to supply a pre-processing function that is applied to the R code before it is executed, which is what I've done in PR #171.

**Comment by daattali** [comment]
Do you know of any other places that expect user input and lets you convert the text like this?
Do you know who is affected by it (is it common for whatever browser you're using to do that based on IP in your country? Is it your OS?)
I'm just trying to understand if this is really something that shinyjs should meddle with. I've never seen this before and the fix you suggest, while it would work, seems like overengineering for a seemingly small issue. Maybe your browser or OS has a feature to disable that? I'm always very conservative about adding parameters, and if it only serves a very specific unique case it's hard to justify it

**Comment by daattali** [comment]
There is no problem with implementation itself per se, just the feature creep aspect. There are many suggestions for additions to be made, and I want to be very deliberate about which improvements actually end up getting implemented because I don't want to add code to support a very small usecase for a very small number of users, **especially** when it feels like it shouldn't be done.

The reason I say I feel it shouldn't be done is because I still 100% feel this is not something that shiny (or any other language you type text into) should deal with - the input needs to be correct. Providing a preprocess function for that input is going to be a confusing feature to most users that they won't understand its purpose, and I frankly don't see any purpose to it beyond your current usecase.

I asked the first question, whether this is standard practice or at least a practice that exists in similar applications because I was willing to consider it if it seemed like there is evidence that this is a real feature that other apps employ. But I just tried a few different "run R code online" and "run JS code online", and in all of them when I typed in a string with smart quotes and pressed Run, it broke. I realize there's one difference: here you can provide a preprocess function and in those online editors you cannot. But I still strongly believe that after seeing this behaviour by all online text inputs I observed, the smart quotes feature is an inconvenience of MacOS and should be dealt with by Mac/the user, and not the end software. There is an implicit understanding that when passing in text, it is well formed, and when passing in strings they are surrounded by quotes. If MacOS decides to do strange things to quotes, the software expecting quotes should not have the burden of accommodating that.

I do really appreciate your contribution and taking it upon yourself to provide the code for a feature you requested, I don't mean to discount any future suggestions, but this feature is not something I think should be added

**Comment by gwarnes-mdsol** [comment]
Based on behavior (e.g. RStudio via the web browser) there is some mechanism (presumably javascript) to prevent the browser from auto-converting standard quotes into open/close.

**Comment by daattali** [comment]
If there's a way to tell the textarea to disable automatic smart quote
conversion, that I wouldn't mind adding!

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
I've been thinking about this and I don't think I would want to explicitly change characters. I also run into issues sometimes when I copy certain characters from one software to another--such as single quotes/double quotes, apostrophes--that they can cause issues. Ultimately I don't think it's within scope for shinyjs to try to deal with this. Maybe it makes sense for the browser to convert the quotes when text is pasted, or maybe R itself. But shinyjs does not feel like the correct step in the pipeline that should be concerned with this.
