### ISSUE TITLE
shinyjs::reset() does not reset elements with spaces in inputId

### ISSUE THREAD

**Issue by Gaffi** [daattali/shinyjs#202]
When trying to reset a form containing elements whose inputId contains spaces, the element is not reset, though any others with no whitespace are. Whitespace may not be an ideal style choice in naming elements, but for my application, it's what I have to work with without rebuilding the entire app.

As an aside, special characters other than spaces seem to perform just fine.

Consider the example below:

```
library(shiny)
library(shinyjs)

runApp(
  shinyApp(
    ui = fluidPage(
      useShinyjs(),
      div(
        id = "form",
        textInput("testone", "Able to be reset", ""),
        textInput("test two", "Not able to be reset", ""),
        textInput("test!three", "Also able to be reset", ""),
        textInput("test$four", "Again able to be reset", "")
      ),
      actionButton("refresh", "Refresh")
    ),
    server = function(input, output, session) {
      observeEvent(input$refresh, {
        shinyjs::reset("form")
      })
    }
  )
)
```

**Comment by daattali** [comment]
Spaces should not be used in IDs. In fact it's illegal in HTML to have spaces in IDs ([source](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id)). I don't consider this a bug because of this, and I would strongly suggest that any IDs you have that contain spaces will be replaced with underscores or other characters.

In general, not just regarding HTML IDs, spaces in names of things in computers are bad and can result in unexpected behaviour.

**Comment by Gaffi** [comment]
I was afraid of that. I'll set out cleaning it all up. Thanks for the speedy response!
