### ISSUE TITLE
reset() function doesn't work with sliderInput that uses dates

### ISSUE THREAD

**Issue by andrea-sottana-MoJ** [daattali/shinyjs#213]
Hi,
I am experiencing an issue with the `shinyjs::reset` function when trying to reset a `sliderInput` on a date range. I've put together this minimal reproducible example. When I click on "Reset dates", instead of resetting them from 2010 to 2020, it uses 13-digit numbers instead. Any idea what might be going on?
My suspicion is that it is displaying milliseconds since 1970, perhaps to do with Javascript's preferred date/time structure. Is there any way to get around this issue?
```
library(shiny)
library(shinyjs)
shinyApp(
    shinyUI(
        fluidPage(
            shinyjs::useShinyjs(),
            sliderInput(
                "dates_filter",
                label = "Select date range",
                min = as.Date("2010-01-01"),
                max = as.Date("2020-01-01"),
                value = c(as.Date("2010-01-01"), as.Date("2020-01-01")),
                timeFormat="%B %Y"
            ),
            actionButton("resetting", "Reset dates")
        )
    ),
    shinyServer(function(input, output){
        observeEvent(input$resetting, {
            shinyjs::reset("dates_filter")
        })
    })
)
```

**Comment by daattali** [comment]
It looks like what happens with `reset` is exactly what would happen if you do `updateSliderInput(session, "dates_filter", value = c(("2010-01-01"), ("2020-01-01")))` (without using `as.Date()` and without using the custom format).

The way shinyjs works is by looking at initial value of the input at page load in the DOM using javascript, and when you call `reset()`, those the appropriate shiny update function (`updateSliderInput()` in this case) is called. Looking at the DOM, the initial values are indeed "1262304000000,1577836800000" as you suspected. For the 5+ years since shinyjs existed, I never ran across a situation where this was not enough information to correctly re-init the input, but it looks like you found a special case!

Again looking at the DOM, this is what I see:

```
<input class="js-range-slider shinyjs-resettable irs-hidden-input shiny-bound-input" id="dates_filter" data-type="double" data-min="1262304000000" data-max="1577836800000" data-from="1262304000000" data-to="1577836800000" data-step="86400000" data-grid="true" data-grid-num="9.97814207650273" data-grid-snap="false" data-prettify-separator="," data-prettify-enabled="true" data-keyboard="true" data-drag-interval="true" data-data-type="date" data-time-format="%B %Y" data-shinyjs-resettable-id="dates_filter" data-shinyjs-resettable-type="Slider" data-shinyjs-resettable-value="1262304000000,1577836800000" tabindex="-1" readonly="">
```

I noticed the `data-data-type="date"` and `data-time-format` attributes that can give hints to have to convert values into dates and use the custom format. So I think that in order to fix this bug, another piece of information will need to be sent to shiny other than the input type and values - perhaps a generic "extra" piece of information that for now would only be used for range sliders that have a non default type ("date" in this case). In an effort to make this work for other non-traditional slider cases, I looked at the [ionrangeslider documentation](http://ionden.com/a/plugins/ion.rangeSlider/api.html) (that's the javascript library used for slider inputs) to see what other `data-data-type` are supported, but unfortunately the docs aren't very helpful because they claim that the only two values allowed are "single" or "double", but the values that I see used are "number" and "date", so I think only experimenting with different values will give a more complete picture.

I'll leave this issue open as it is indeed a bug, but I don't think I'll get around to it due to its low pirority and lack of time on my end. I would be happy to welcome a PR from anyone.

**Comment by andrea-sottana-MoJ** [comment]
Thanks a lot for investigating and for your detailed reply.
One solution I found, short of using `updatesliderInput` (which would prevent me from using the `reset` function to update everything else in one go), is to use `dateRangeInput` instead of `sliderInput`, which seems to work fine with `reset` (example below).
It's nowhere near as nice for the user if they need to change dates flexibly and frequently, but at least it works.
```shinyApp(
    shinyUI(
        fluidPage(
            shinyjs::useShinyjs(),
            dateRangeInput("dates_filter","select dates", 
                           start=as.Date("2010-01-01"),end=as.Date("2020-01-01")),
            actionButton("resetting", "Reset dates")
        )
    ),
    shinyServer(function(input, output){
        observeEvent(input$resetting, {
            shinyjs::reset("dates_filter")
        })
    })
)
```
I'd be keen though to watch this space and see if anyone comes up with a quick fix.

**Comment by daattali** [comment]
Yes using shiny's date inputs would be a very sensible approach here. To be honest I never saw the slider input used as a date ranger picker, but I can see why if you need to make a lot of changes often it might be more user friendly than the traditional calendar date picker.

I'm still keeping this open since it is a real (albeit low pri) bug.

**Comment by daattali** [comment]
@andrea-sottana-MoJ `reset()` now works with both dates and date-times within slider inputs
