### ISSUE TITLE
Embedding shinyjs in markdown document without explicit ui, server pair

### ISSUE THREAD

**Issue by rozsasarpi** [daattali/shinyjs#22]
Is it possible to use `shinyjs` functions when the ui and server pair is not explicitly defined (see example __2__)?

I would like to use a shiny app embedded in a markdown document, and it is convenient not to define explicitly the server and ui, e.g. markdown text can be put between code chunks of input and output elements. This approach is working with `shiny` functions but not with `shinyjs`. Please see the two examples below. Is there any way to use `shinyjs` for cases given in example __2__, or maybe this approach show be avoided if possible?

__1: with explicit definition of ui and server__
```
---
title: "with ui and server"
runtime: shiny
---

Press the button.

```{r, echo = F}
library(shiny)
library(shinyjs)

shinyApp(
  ui = fluidPage(
    shinyjs::useShinyjs(),
    actionButton("submit", "Click me!"),
    shinyjs::hidden(
      span(id = "submitMsg", "Message!", style = "margin-left: 15px;")
    )
  ),
  
  server = function(input, output, session) {
    observeEvent(input$submit, {
      shinyjs::toggle("submitMsg")
    })
  }
)
#``` #not commented but github thinks this is the end of the first block
```

__2: without explicit definition of ui and server__
```
---
title: "without ui and server"
runtime: shiny
---

Press the button.

```{r, echo = F}
library(shiny)
library(shinyjs)

fluidPage(
  shinyjs::useShinyjs(),
  actionButton("submit", "Click me!"),
  shinyjs::hidden(
    span(id = "submitMsg", "Message!", style = "margin-left: 15px;")
  )
)

observeEvent(input$submit, {
  shinyjs::toggle("submitMsg")
})
#``` #not commented but github thinks this is the end of the first block
```

**Comment by daattali** [comment]
Hmm to be honest I never really thought of using shinyjs inside documents because docs are more for showing information whereas shinyjs is more useful for interactive applications.  I'm not quite sure how the rmarkdown system works with shiny.  If anyone has much experience with using javascript inside rmarkdown and wants to help support this or at least provide me with some tips, that'd be awesome, but I don't have the bandwidth to look into that myself.

**Comment by daattali** [comment]
One problem is that I don't even know how (or if it's even possible) to include a CSS or JavaScript file in an Rmarkdown document running shiny.  I'm too much of a noob when it comes to shiny in rmarkdown, but I'll take a look

**Comment by daattali** [comment]
Adding some info here so that I can add rmarkdown support in the future: Joe Cheng told me how to add resources in an rmd doc, but I'm still unsure of how to efficiently use a function that adds resources to both a shiny app and an interactive doc

https://groups.google.com/forum/#!topic/shiny-discuss/0aO5Jc6CP1Y

**Comment by rozsasarpi** [comment]
Thank you for the update and for your effort!

**Comment by daattali** [comment]
Hi @rozsasarpi , I think it should work now.
