### ISSUE TITLE
Abililty to add/remove a new attribute by selector

### ISSUE THREAD

**Issue by federiva** [daattali/shinyjs#235]
I'm using some functions to do this actually using your excellent package. 
Maybe something following the idea of shinyjs::addClass/removeClass?  but with attributes?

**Comment by daattali** [comment]
Thanks for the suggestion. I would prefer not to add this function as I think it isn't going to be widely applicable, and I try to keep the set of exported functions small so that the package is specialized for doing the most common operations. Otherwise there would be hundreds of functions and it would become unmanageable for me and daunting for users. I would keep using custom functions for adding attributes (I do that as well. There are lots of functions i use extendShinyjs for, and only rarely I think something is important enough to add to shinyjs)

**Comment by federiva** [comment]
Yeah I thought that that may be the reason for not seeing it over here. Thanks for the fast reply and congratulations for this awesome package!
