### ISSUE TITLE
Possible to control direction of the "slide" animation?

### ISSUE THREAD

**Issue by mbacou** [daattali/shinyjs#28]
This is just a quick question. When `anim==TRUE` is there a way to control the direction of the "slide" animation (seems default is "from top", I'd be looking for "from left" and right as well).
Thx!

**Comment by daattali** [comment]
Hi, that behaviour is not natively supported, but if you really want you can implement this behaviour yourself

If you're comfortable doing it, here's a reference on how to "slide" animate using jQuery
http://api.jqueryui.com/slide-effect/

**Comment by AbrahamEyman** [comment]
any update on this? adding native slide directions seems like a worthy endeavor for shinyjs.

**Comment by daattali** [comment]
There are no plans on supporting this functionality. It would be simple to implement (see link above), but in order to avoid feature creep I don't want to add another esoteric parameter to hide/show. There's a balance between accepting feature requests and ending up with a laundry list of parameters, and I try to be conservative about adding new funcitonality only if it seems to be important for a large number of users.
