### ISSUE TITLE
Requesting added capability to delay functions when launched

### ISSUE THREAD

**Issue by Stephen-McDaniel** [daattali/shinyjs#35]
With complex applications, you may want to disable and then enable controls once data refresh is complete. While this works well in simpler apps, with more complex apps, it is quite difficult to position enable in the right spot (ideally, it would be after all possible changes have occurred.) 

I would ask for an asynchronous delay option (in ms or seconds) on function calls.  This way, you could send the request to the browser without stopping final updates to the client.  I am not a JS expert, so maybe I am missing a simple route to achieve a similar outcome.

BTW, a great package, thanks!

**Comment by daattali** [comment]
Hi @Stephen-McDaniel 

Thanks for the suggestion. This is something I've been thinking about many times before, but I wasn't able to find a nice simple solution for this. I added a `delay` parameter to a few functions, did you know that you can add a `delay` argument to `show`/`hide`/`toggle`?  

Unfortunately I couldn't find a way to generalize it.  Ideally, I wanted to be able to have a function called `delay` that will work like this

```
shinyjs::delay(1000, shinyjs::hide("message"))
shinyjs::delay(2000, shinyjs::reset("text"))
```

If you have any ideas, I'm open to pull requests. I don't know how to (or if it's even possible) do asynchronous delays in R, and I think this would have to be implemented in R because some functions (for example, `reset` and `onclick`) are not purely javascript functions.

**Comment by daattali** [comment]
@Stephen-McDaniel I thought of a way to do this and added a `delay` function. I hope this is what you wanted and will work for you. Please let me know if you run into any problems

**Comment by Stephen-McDaniel** [comment]
@daattali excellent!  Works quite well in my described scenario above.

I hope to see you at next years R Conference, will buy you a drink (or two!)

Cheers,
Stephen

**Comment by daattali** [comment]
Haha I REALLY wanted to go this year but couldn't because of a doctor
appointment :/ Glad to know it's what you wanted

**Comment by Stephen-McDaniel** [comment]
Sorry to hear that! It was a great conference. Highlights included watching R programmers being tied to trees by pirates and hatchet throwing.  Lawyers in US would never allow either, especially with all the drinks at the closing picnic!

BTW, this seems to be working great on several projects.

**Comment by daattali** [comment]
Yup that's what I saw on Twitter, I was thoroughly jealous. I'm glad you brought up this delay issue because I kind of gave up on it and needed the extra nudge
