### ISSUE TITLE
Many more Could not find DOM element errors with 0.2.0

### ISSUE THREAD

**Issue by jonkeane** [daattali/shinyjs#38]
I recently updated to 0.2.0, and I've noticed a large increase in `shinyjs: Could not find DOM element` errors. So far I haven't seen much impact on actual functionality, but should I worry about these?

**Comment by daattali** [comment]
Those aren't errors, it just says that internally it was looking for elements and they don't exist. It's more for debugging than anything. It's normal to get these messages, especially now that I added support for dynamically generated elements, because a lot of times shinyjs will look for elements without knowing if they exist yet or not. It's an unfortunate side effect or supporting dynamic element creation. Is there a specific function or code snippet you found generates a lot of these? Maybe I can look into trying to optimize it

**Comment by jonkeane** [comment]
Ok, thanks for the reply, that's good to know! 

The function I'm using currently is toggleState() to check that all fields of a few different forms are filled in.  I think what's probably going on is that only some of the fields are displayed some of the time, so it is unable to find the elements that are not currently being displayed.

**Comment by daattali** [comment]
Ok, thanks for the report. As long as you aren't experiencing any problems, it should be fine.  Perhaps I should turn off all these messages and have a "debug" flag that's false by default, but if you turn on it then you'll get console messages that will be helpful if you run into problems.

**Comment by daattali** [comment]
I made two fixes: 1. the messages you saw should appear much less often, 2. by default, all such messages are turned on.  You can turn them on, along with other detailed debugging  information, by calling `useShinyjs(debug = TRUE)` instead of just `useShinyjs()`
