### ISSUE TITLE
Using an extendShinyjs function in session$onFlushed

### ISSUE THREAD

**Issue by jonkeane** [daattali/shinyjs#39]
Sorry for another issue so soon. On the update, I also noticed that I can't seem to use `extendShinyjs` functions inside of `session$onFlushed`. When I try, I get there error 

```
Error in (structure(function (input, output)  : 
  object 'session' not found
```

Reproducible code is:

```
library(shiny)
library(shinyjs)

server <- function(input, output) {
  session$onFlushed(function(){
    js$test()
  })
}

ui <- fluidPage(
  useShinyjs(),
  extendShinyjs(text="shinyjs.test = function(params){console.log('test');}"),
  h1("test")
)

shinyApp(ui = ui, server = server)
```

I've already fixed this in the code I'm working on by just using `session$sendCustomMessage` which for my purposes are fine, so there's no huge issue for me, but this did work in a previous version.

**Comment by daattali** [comment]
I haven't run your code but I can see a problem right away: you're not declaring a session parameter in the server function.

**Comment by daattali** [comment]
I see what you mean now. If you do add the session parameter as needed by shiny, then shinyjs has an error where it can't find the session.  I'll look into that. Do you mind showing me what you're trying to do? I never used to onFlush callback and don't fully understand the reactive contexts when you're inside a session callback so I want to see the usecase to better understand it

**Comment by jonkeane** [comment]
Sorry for that, I tried to make a minimal example, and totally forgot to include the session argument. 

The use case is a bit not what shiny was designed for: I'm developing an online (psycholinguistic) experiment where people are presented with videos of a word being signed in american sign language, and they are asked to type the word.

I'm using javascript here to insert the video into the document where it needs to be either from the pre-cache that has been downloaded or directly from the server. I'm using sessionOnFlushed so that I know that the page is fully loaded with respect to shiny's work before I start trying to find and insert objects into the DOM.

https://github.com/jonkeane/fingerspellingPerceptionExperiment/blob/b4aeee3c4630262b43d689b00cf75d54c7399cb1/server.R#L205-L207 has the old code using `extendShinyjs` which doesn't seem to work
https://github.com/jonkeane/fingerspellingPerceptionExperiment/blob/master/server.R#L213-L215 has the custom message instead, which does work now.

I should apologize ahead of time for the state of the above linked code, it's very actively in development and I haven't had a chance to go back, clean it up, and comment it as much as I would like.

**Comment by daattali** [comment]
Thanks for the details.  Just as a note to self and others: this isn't only a problem with `extendShinyjs` - any shinyjs function currently won't work inside a session callback (`onFlush`/`onFlushed`/`onEnded`). I was quite stumped by why my code doesn't work in those callbacks so I asked [on the Shiny discussion board](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/shiny-discuss/_-9piBSa7kw/IHXQDfzo-PMJ) and Joe (creator of shiny) told me that it actually is a bug with shiny they were unaware of, so now there's a bug [files with shiny](https://github.com/rstudio/shiny/issues/956) and they will probably fix it soon. 

FYI it used to work because in older versions of shinyjs you were required to define the `session` parameter and my shinyjs code would try to find the `session` variable by climbing up the stack frames until it saw it.  But that was a little bit hacky, and then Joe told me that they proper way to find the session is with a special shiny function.  But it looks like that shiny function has a bug.

I'll leave this issue open and close it when it gets fixed on Shiny's end

**Comment by daattali** [comment]
This seems to have been mostly fixed. You can use shinyjs inside `session$onFlush()` and `session$onFlushed()` , but `session$onSessionEnded()` still doesn't seem to know about the `session` object.
