### ISSUE TITLE
[Question] How to override a variable created by a mouseclick event

### ISSUE THREAD

**Issue by happyshows** [daattali/shinyjs#63]
For example,

I'm using a mouse click listener in rAmCharts which will trigger the creation/override of input object: clickedVal  when use click the objects in the diagram.
 addListener(name = 'clickGraphItem', expression = paste0('function(event){',
                                                                 'Shiny.onInputChange(\'clickedVal\', event.item.category)',
                                                                 '}'))

In some cases, I need to reset input$clickedVal to '' or NULL. Shiny won't allow me to modify the input value directly. Is there anything runjs can do?

Thanks.

**Comment by daattali** [comment]
I don't understand the question, mainly because I'm unfamiliar with that package. You'll have to write a full minimally reproducible example. But https://groups.google.com/forum/#!forum/shiny-discussif I understand right, your main problem is mofidying an input from a value to `NULL`?  If that's the problem, I suggest asking in a Shiny discussion board
