### ISSUE TITLE
hidden() does not have the expected behaviour with tabs

### ISSUE THREAD

**Issue by KZARCA** [daattali/shinyjs#71]
It doesn't hide the tab menu (ul > li), but the tab-content.

**Comment by daattali** [comment]
I understand why that seems strange, but that's not something I can fix from shinyjs because tabs are just a very weird thing in shiny and they don't follow normal rules.  Calling hide/show on a tab won't work either because of how they work, and there's a lot of other annoyances with tabs.... so unfortunately `hidden()` is also one of these things that just don't work out of the box with tabs. Sorry!

**Comment by KZARCA** [comment]
OK, thank you.
I was able to use hide like that, but there is latency:
`hide(selector = "#menu [data-value='menuResults']")`
#menu is the id of tabsetPanel, and 'menuResults' is the value of the tab.

**Comment by daattali** [comment]
Yeah, that will work, I've given that solution a few times before, though I didn't notice any lag. But that's what I meant by "out of the box" - if you want to make anything work with tabs, it won't be pretty :)
