### ISSUE TITLE
toggleState doesn't always work in renderUI

### ISSUE THREAD

**Issue by carlganz** [daattali/shinyjs#74]
Hey Dean,

Hope all is well. I have found that `toggleState` doesn't work for an object created in a `renderUI` if the `renderUI` has an `input` in it. Here is an example:

```{R}
library(shiny) 
library(shinyjs)

shinyApp( 
  ui = fluidPage(
    useShinyjs(),
    selectizeInput("one","On and Off",c("ON","OFF"),"ON"),
    uiOutput("two"),
    uiOutput("three")
    )
  , 
  server = function(input, output,session) {     
    
    output$two <- renderUI({
      selectInput("two",input$one, letters)
    })
    
    output$three <- renderUI({
      selectInput("three","static label",letters)
    })
    
    observe({
      shinyjs::toggleState("two",condition=input$one=="ON")
      shinyjs::toggleState("three",condition=input$one=="ON")
    })
    
  }
)
```

I'm guessing the issue is that the UI object rendered server-side is rerendered whenever the state is toggled so it never gets toggled out. 

Kind Regards

**Comment by daattali** [comment]
I don't think I would consider this a bug. You're right, what happens is that the input gets re-rendered. When the input gets re-rendered, its state is lost, and this is the expected behaviour (just like the selected value of the input is also lost, and it's expected).

However, what you are trying to do can be achieved by using the `disabled()` function to initialize the input as disabled.  Something like this should work:

```
shinyApp( 
  ui = fluidPage(
    useShinyjs(),
    selectizeInput("one","On and Off",c("ON","OFF"),"ON"),
    uiOutput("two"),
    uiOutput("three")
  )
  , 
  server = function(input, output,session) {     
    
    output$two <- renderUI({
      if (input$one=="ON") {
        selectInput("two",input$one, letters)
      } else {
        disabled(selectInput("two",input$one, letters))
      }
      
    })
    
    output$three <- renderUI({
      selectInput("three","static label",letters)
    })
    
    observe({
      shinyjs::toggleState("three",condition=input$one=="ON")
    })
    
  }
)
```
