### ISSUE TITLE
disable does not work when using updateCheckboxGroupInput()

### ISSUE THREAD

**Issue by KZARCA** [daattali/shinyjs#76]
Hi Dean,
The following code doesn't make the "checktest" input to disable. 

    library(shiny)
    library(shinyjs)

    runApp(list(ui =
      shinyUI(fluidPage(
         useShinyjs(),
         fluidRow(
            column(6, id = "test",
               checkboxGroupInput("checktest", NULL, choices = letters[1:10]),
               actionButton("okcheck", "OK")
            )
         )
       )
      ),
      server = shinyServer(function(input, output, session) {
        observeEvent(input$okcheck,{
          updateCheckboxGroupInput(session, "checktest", NULL, choices = letters[11:20])
          disable("checktest")
        })
     })
    ))

However:
- It works when I remove updateCheckBoxInput.
- It works when I use updateSelectInput instead
- It doesn't work with updateRadioButtons
- When using hide() instead of disable(), it works.

Best regards

**Comment by daattali** [comment]
Thanks for the very detailed bug report, I do appreciate when you take the extra time to format things nicely and do a bit of debugging to know what conditions do and do not work.  But I'm sorry to tell you this isn't going to be fixable.

Explanation: The way `disable()` works is that in JavaScript it disables the input. For most inputs this is fairly trivial as there is only one element to disable. But with radio buttons or checkbox groups, that won't work because every single item needs to be disabled individually. So when you disable eg. a text input, you can later update the text input and it'll still be disabled because it's still the same element, the only thing that changes is its value.  But with checkboxgroups, when you update the value, shiny actually writes new HTML elements for each of the options, and these new elements are not disabled by default. I think because of the way shiny handles javascript messages, the update actually happens a bit later then the disable call. You might notice some slight quick flickering every time you click the button, which is the result of disabling all the options and immediately afterwards re-writing them with new HTML.

The reason why `hide()` works is because hide is just called on the parent element of all the options, so it doesn't matter if the individual options are re-written because their ancestor is already hidden.

The reason that select inputs works is because in a select input only the parent select html element needs to be disabled, and when you update the value, it doesn't matter if you add new HTML elements -- as long as the parent is disabled, the entire dropdown is disabled.

I hope this makes sense.  But bottom line: because of the way shiny works, this is not solvable (unless shiny decides to manually disable input options when it updated values and notices that the parent is disabled, but I really doubt they have the bandwidth for such a specific bug).  Sorry!

**Comment by KZARCA** [comment]
Oh, that's too bad, thank you for the explanation, that's really clear.

**Comment by nmsz97** [comment]
Please don't mislead by saying it is not possible, anything is possible. Simply add:

```
$(document).on('shiny:inputchanged', function(event) {
  if (event.name === 'IDOFPARENTDIV') {
    $("#IDOFPARENTDIV :input").attr("disabled", true);
  }
});
```
to a JS file and import it into the R code.

**Comment by daattali** [comment]
@nmsz97 I just got an email from you commenting on this issue, telling me that I mislead people when I said it's not possible? Everything is indeed solveable with javascript, but I meant this is not something I can solve from shinyjs' end.

If you indeed had a nice short solution please post it again

**Comment by nmsz97** [comment]
Ill see if I can put up my code but I deleted it because I didnt like my tone towards you. Thanks

**Comment by daattali** [comment]
That's fair - if only there was a way to delete outgoing emails :)

**Comment by maxpohlman** [comment]
Ran into this issue today and this thread was the first thing that popped up on google. To any other future readers, I was able to work around this issue by putting the shinyjs::disable() command inside of a 1ms delay(). That way the browser renders the new checkboxes first, then applies the delayed disable. Not the most elegant of solutions, but worked for me.

`
library(shiny)
library(shinyjs)

runApp(list(ui =
              shinyUI(fluidPage(
                useShinyjs(),
                fluidRow(
                  column(6, id = "test",
                         checkboxGroupInput("checktest", NULL, choices = letters[1:10]),
                         actionButton("okcheck", "OK")
                  )
                )
              )
              ),
            server = shinyServer(function(input, output, session) {
              observeEvent(input$okcheck,{
                updateCheckboxGroupInput(session, "checktest", NULL, choices = letters[11:20])
                #disable("checktest") # Does not work
                delay(1,disable("checktest")) # Works
              })
            })
))
`

**Comment by daattali** [comment]
I believe it would also work with a delay of 0ms. The call to update the checkboxes doesn't happen immediately, so the `disable()` function is essentially disabling the checkboxes before they get updated. A delay of 0ms is not really only "wait 0ms", it also means that you need to wait until other actions have completed, that's why it works.
