### ISSUE TITLE
default values

### ISSUE THREAD

**Issue by MikeBadescu** [daattali/shinyjs#80]
Thank you for the great package!

Would it be possible to specify default values in the formals of functions like `show()`, `hide()` and `toggle`? The default values are mentioned in the documentation but not in the source code. Similarly, `selector` in `enable()`, `disable()` could be NULL by default.

This is mostly an annoyance since RStudio is showing Code Diagnostic warnings such as `argument 'id' is missing, with no default`.

**Comment by daattali** [comment]
When exactly do you see this error? The default values are on the
Javascript by the way

**Comment by MikeBadescu** [comment]
This is what I see in RStudio 0.99.1293 (but for many previous versions as well), R 3.3.1 x64 on Windows 10.

![shinyjs-warn1](https://cloud.githubusercontent.com/assets/6641575/17979355/c9a6ab86-6abf-11e6-843b-74f3a294336c.png)
![shinyjs-warn2](https://cloud.githubusercontent.com/assets/6641575/17979357/c9af57c2-6abf-11e6-9182-16fb9be3954c.png)

**Comment by daattali** [comment]
I do see that now if I enable all the code diagnostics.  I find that quite annoying, but more so on RStudio's part.  I wouldn't consider this a problem with shinyjs personally. I don't think it's bad practice to have arguments to a function and not give them default values.  I would strongly argue that this should not be a "warning" at all, it's a very normal thing to have missing arguments.  But maybe the RStudio guys believe otherwise, in which case I'll consider adding defaults.

**Comment by MikeBadescu** [comment]
My (subjective) view is that having no default value for an argument implies that the argument must be supplied. Also, style guidelines (e.g. spacing) are not required in R, but they make the code readable. Thank you for considering this.

**Comment by daattali** [comment]
I do see your point, and I will agree with you in general, but the shinyjs functions have all their default values set in the javascript.  Initially I just had "..." as the arguments to the functions because all the args are just passed directly into javascript and it's important not to touch them in any way before, and I just documented in the docs what the actual arguments are. But later on I decided it's much better for users to be able to see exactly what arguments are used, so I added the arguments explicitly.  But I don't want to give them defaults in R because then they'll have duplicate default values in two places and that feels very wrong, and simply passing along all the params seems like the more correct solution.  If javascript was not involved and the entire function was just implemented in R then I'd agree with you, default values would make more sense.  And I don't want to just use NULL as default values because in some cases NULL is actually meaningful but sometimes it isn't.

**Comment by MikeBadescu** [comment]
I have run into the double defaults issue, it helps to have only one source of defaults, either in the upstream function or in a helper function / dictionary. I am not sure how it would work with JS (not a JS expert). It would be great if it were possible.

(speculating) Maybe the string `'null'` could be a default for passing `NULL`.

Also, thank you for taking your time and asking the community.

**Comment by daattali** [comment]
You can see how the default values are assigned in JS: [here](https://github.com/daattali/shinyjs/blob/master/inst/srcjs/shinyjs-default-funcs.js#L475-L494) and [here](https://github.com/daattali/shinyjs/blob/master/inst/srcjs/shinyjs-default-funcs.js#L126-L134) as an example.  The nice thing is that I don't have to worry about what params are passed in and which aren't - JavaScript has a nice "extend" function that deals with that.  I really can't think of any way to share common default value between both R and JS...

**Comment by daattali** [comment]
FYI I'm starting to agree with you and think that default values should be provided, but for different reasons. The rstudio warnings are a bit annoying but they shouldn't rule how I write my code :package: 

My reason is that I think for the end user it's more convenient to see the default values when they autocomplete the function rather than having to read the documentation to see what they are. I might do that for the next version.

**Comment by MikeBadescu** [comment]
Good point. But it will affect many functions ... either use new function names and deprecation warnings or go for shinyjs2 😄

**Comment by daattali** [comment]
I will use the same defaults that currently exist, the only difference is
that they will be defined in R instead of in JS. It shouldn't break
anybody's code

**Comment by daattali** [comment]
@MikeBadescu I finally got around to doing this.

I'm very scared something may have broken. If you have a chance at some point, I'd appreciate if you could install from github and make sure your apps still work

**Comment by MikeBadescu** [comment]
Dean, thank you! 

I installed from GitHub and tested it - so far no issues.

**Comment by daattali** [comment]
Awesome. I've done a lot of changes so you might run into some issue
somewhere:)
