### ISSUE TITLE
Error in observeEventHandler: attempt to apply non-function Stack trace (innermost first)

### ISSUE THREAD

**Issue by earthcli** [daattali/shinyjs#83]
when I use a js function refer to this link:
http://stackoverflow.com/questions/32104918/how-to-manually-collapse-a-box-in-shiny-dashboard, 

jsboxcollapsecode <- "shinyjs.collapse = function(boxid) {
$('#' + boxid).closest('.box').find('[data-widget=collapse]').click();
}
"
and I have put useShinyjs(),extendShinyjs(text=jsboxcollapsecode) in the UI, while using a observeEvent in the server:
 
 observeEvent(input$sidebarmenu,{
      js$collapse("parbox")
  })

I have test the example of the link, it works well on my computer, while for my app, I have preparelly generate the ui in my package, and wrap it in a function, 

require(mypackage)
data(ui)
app=shinyApp(ui,server)
runApp(app,host=ip,port=port,launch.browser=TRUE)

I got an error "Error in observeEventHandler: attempt to apply non-function Stack trace (innermost first)", it seems the js$collapse is not recognised in the server, may be due to some environment setting, How to sove it ?

generally, I have preparedly created the UI and server function, and then include in my package, and then I load the app in a function, I have test that it works when I create the UI and server and run app in the same script(that means not by load ui and server function seperately), so it may be due to the global environment seeting.

**Comment by earthcli** [comment]
finally, this works, by load the js function with onStart parameter, but i do not know how it works.

require(mypackage)
data(ui)
loadjs<- function() {
  require(shinyjs)
  data(jsboxcollapsecode,package="myshiny")
  useShinyjs()
  extendShinyjs(text=jsboxcollapsecode)
}
app=shinyApp(ui, server, onStart=loadjs)
runApp(app,host=ip,port=port,launch.browser=TRUE)

**Comment by earthcli** [comment]
and another question, with the above code I can get the box change between collapsed and uncollapsed, with clicking the sidebar menuItem, but I want to keep the box uncollapsed when the menuItem is clicked, while only when the actionButton is clicked ,the box should be collapsed. what the code should be for keep uncollapsed?

**Comment by daattali** [comment]
I'm glad you answered you own question. In the future, try to include a full minimal reproducible example because it's hard for me to understand the problem when I don't have code to run. In regards to your last question, I'm not too sure off the top of my head how to tell a box to be collapsed or uncollapsed. All that my javascript code is doing (from the stackoverflow answer) is simulate a click on a button, it doesn't know anything about the states of the boxes.

You'll have to look into the CSS/Javascript of the boxes to figure out exactly what to change. You can contact me privately if you want help
