### ISSUE TITLE
Enter clicks button

### ISSUE THREAD

**Issue by danielsjf** [daattali/shinyjs#97]
It would be nice to activate a certain button when clicking enter in an input field. Something along the lines of:

    shinyjs::enter_activate("Actionbutton")

There is an example here:
http://stackoverflow.com/questions/32335951/using-enter-key-with-action-button-in-r-shiny

**Comment by daattali** [comment]
Hi Jef,

Did you see my solution for this in my recent blog post?
https://github.com/daattali/advanced-shiny/tree/master/proxy-click

You can also do it with the new "shinyjs::onevent()" that supports telling
you what key was pressed (you can use onevent("keyup", function(e){ key =
e.which ...})

I did briefly consider adding this functionality to shinyjs but decided
against it because it doesn't feel like a core enough feature that enough
people would use so instead I just added it to my blog post of "tricks you
can do"

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by danielsjf** [comment]
No sorry I missed this one! Thanks.
